# This is the CI configuration file

[general]
prompt = false

[packages]
acid = {}
#autoconf = {}
#automake = {}
bash = {}
binutils = {}
ca-certificates = {}
#cargo = {}
cleye = {}
#cmatrix = {}
contain = {}
coreutils = {}
#curl = {}
dash = {}
#diffutils = {}
#dosbox = {}
drivers = {}
#drivers-041 = {}
#duktape = {}
expat = {}
extrautils = {}
#fd = {}
#ffmpeg = {}
findutils = {}
freedoom = {}
#freetype = {}
game-2048 = {}
games = {}
#gawk = {}
gcc = {}
generaluser-gs = {}
#gigalomania = {}
#git = {}
gnu-binutils = {}
#gnu-grep = {}
gnu-make = {}
init = {}
installer = {}
ion = {}
ipcd = {}
#jansson = {}
keyboard-sfx = {}
#lci = {}
libjpeg = {}
liborbital = {}
libpng = {}
libsodium = {}
logd = {}
#lua = {}
#mdp = {}
#miniserve = {}
nasm = {}
#ncdu = {}
#ncurses = {}
#ncursesw = {}
netdb = {}
netstack = {}
netsurf = {}
netutils = {}
#newlib = {}
#newlibtest = {}
nulld = {}
openssl = {}
#openttd = {}
#openttd-opengfx = {}
#openttd-openmsx = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
pastel = {}
#patch = {}
periodictable = {}
#perl = {}
pixelcannon = {}
pkgutils = {}
powerline = {}
prboom = {}
ptyd = {}
#python = {}
randd = {}
#readline = {}
redoxfs = {}
#redox-ssh = {}
relibc = {}
ripgrep = {}
rs-nes = {}
#rust = {}
rust64 = {}
rustual-boy = {}
sdl = {}
sdl_image = {}
sdl_mixer = {}
#sed = {}
shellstorm = {}
smith = {}
sodium = {}
#ssh = {}
terminfo = {}
termplay = {}
#timidity = {}
ttf-hack = {}
userutils = {}
uutils = {}
#vim = {}
#vttest = {}
#xz = {}
zerod = {}
zlib = {}
